VehicleDBProject/VehicleDBWebProject/VehicleMVC/Models/ErrorViewModel.cs
using System;

namespace VehicleMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VehicleDBProject/VehicleDBWebProject/VehicleMVC/Models/VehicleMakeDTO.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VehicleMVC.Models
{
    public class VehicleMakeDTO
    {
        public int VehicleMakeId { get; set; }
        [Required]
        public string Name { get; set; }
        public string Abrv { get; set; }
    }
}

VehicleDBProject/VehicleDBWebProject/VehicleMVC/Models/VehicleModelDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VehicleMVC.Models
{
    public class VehicleModelDTO
    {
        public int VehicleModelId { get; set; }

        public int VehicleMakeId { get; set; }

        public string Name { get; set; }

        public string Abrv { get; set; }

        public virtual VehicleService.VehicleMake VehicleMake { get; set; }
    }
}

VehicleDBProject/VehicleDBWebProject/VehicleMVC/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using VehicleMVC.Models;
using VehicleService;

namespace VehicleMVC.Controllers
{
    public class ModelController : Controller
    {
        private readonly IVehicleModelService ModelService;
        private readonly IMapper Mapper;
        public static int NumberOfElements = 5;
        public static int ElementsGot = 0;
        public static int CurrentPage = 1;
        public static string CurrentOrder;
        public static string CurrentSort;

        public ModelController(IVehicleModelService modelService, IMapper mapper)
        {
            ModelService = modelService;
            Mapper = mapper;
        }
        public IActionResult Index([Bind("SearchName")] Filtering makeFiltering, Sorting sorting, Paging paging)
        {
            if (paging.PageNumber == 1)
            {
                ViewBag.OrderBy = sorting.OrderBy == "DESC" ? "ASC" : "DESC";
                CurrentOrder = sorting.OrderBy;
                CurrentSort = sorting.SortBy;
            }

            if (String.IsNullOrEmpty(sorting.SortBy))
            {
                sorting.SortBy = "Name";
                sorting.OrderBy = "ASC";
            }

            paging.TotalPages = ModelService.CountModels();

            CurrentPage = paging.PageNumber;
            ElementsGot = paging.Elements;

            #region HasNextButton
            if ((ElementsGot + NumberOfElements) < paging.TotalPages)
            {
                ViewBag.HasNext = true;
            }
            else
            {
                ViewBag.HasNext = false;
            }
            #endregion
            #region HasPrevButton
            if (paging.HasPreviousPage)
            {
                ViewBag.HasPrevious = true;
            }
            else
            {
                ViewBag.HasPrevious = false;
            }
            #endregion
            #region Search
            if (!String.IsNullOrEmpty(makeFiltering.SearchName))
            {
                if (!ModelService.HasNameInDatabase(makeFiltering.SearchName))
                {
                    return NotFound(makeFiltering.SearchName + " not Found");
                }
                string countQuery = String.Format("SELECT * FROM dbo.VehicleModels Where Name = '{0}'", makeFiltering.SearchName);
                paging.TotalPages = ModelService.GetVehicleModels(countQuery).Count();
                ElementsGot = 0;
                string searchQuery = String.Format("SELECT * FROM dbo.VehicleModels Where Name = '{0}' ORDER BY {1} {2} OFFSET {3} ROWS FETCH NEXT {4} ROWS ONLY", makeFiltering.SearchName, sorting.SortBy, sorting.OrderBy, ElementsGot, NumberOfElements);
                var searchMake = ModelService.GetVehicleModels(searchQuery).Select(Mapper.Map<VehicleModelDTO>);
                #region HasNextButton
                if ((ElementsGot + NumberOfElements) < paging.TotalPages)
                {
                    ViewBag.HasNext = true;
                }
                else
                {
                    ViewBag.HasNext = false;
                }
                #endregion
                #region HasPrevButton
                if (paging.HasPreviousPage)
                {
                    ViewBag.HasPrevious = true;
                }
                else
                {
                    ViewBag.HasPrevious = false;
                }
                #endregion
                return View(searchMake);
            }
            #endregion
            string query = String.Format("SELECT * FROM dbo.VehicleModels ORDER BY {0} {1} OFFSET {2} ROWS FETCH NEXT {3} ROWS ONLY", sorting.SortBy, sorting.OrderBy, ElementsGot, NumberOfElements);
            var make = ModelService.GetVehicleModels(query).Select(Mapper.Map<VehicleModel, VehicleModelDTO>);
            return View(make);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Makers = ModelService.GetMakes();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(VehicleModelDTO vehicleModelDTO)
        {
            if (ModelState.IsValid)
            {
                var vehicleModel = Mapper.Map<VehicleModel>(vehicleModelDTO);
                await ModelService.AddVehicleModelAsync(vehicleModel);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            VehicleModelDTO modelDTO = Mapper.Map<VehicleModelDTO>(await ModelService.GetOneVehicleModelAsync(id));
            return View(modelDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VehicleModelDTO vehicleModelDTO)
        {
            VehicleModel model = Mapper.Map<VehicleModel>(vehicleModelDTO);
            await ModelService.UpdateAsync(model);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (id.Equals(null))
            {
                return NotFound();
            }

            await ModelService.DeleteVehicleModelAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

VehicleDBProject/VehicleDBWebProject/VehicleMVC/Views/Model/Create.cshtml
@model VehicleModelDTO
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form method="post">
    <div><select asp-for="VehicleMakeId" asp-items="@(new SelectList(ViewBag.Makers, "VehicleMakeId", "Name"))"><option value="">--Select--</option></select> /></div>
    <div>Name: <input asp-for="Name" /></div>
    <div>Abrv: <input asp-for="Abrv" /></div>
    <input type="submit" />
</form>

VehicleDBProject/VehicleDBWebProject/VehicleMVC/Views/Model/Edit.cshtml
@model VehicleModelDTO
@{
    ViewData["Title"] = "Edit";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>@Model.Name</legend>

        @Html.HiddenFor(model => model.VehicleModelId)

        <div>@Html.LabelFor(model => model.VehicleMakeId)</div>
        <div>@Html.EditorFor(model => model.VehicleMakeId)</div>

        <div>@Html.LabelFor(model => model.Name)</div>
        <div>@Html.EditorFor(model => model.Name)</div>

        <div>@Html.LabelFor(model => model.Abrv)</div>
        <div>@Html.EditorFor(model => model.Abrv)</div>

        <p><input type="submit" value="Save" /></p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VehicleDBProject/VehicleDBWebProject/VehicleMVC/Views/Model/Index.cshtml
@model IEnumerable<VehicleModelDTO>
@{
    ViewData["Title"] = "Vehicle Models";
}

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by Name: <input type="text" name="SearchName"/>
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<div>
    <table border="1">
        <thead>
            <tr>
                <th align="center"><a asp-action="Index" asp-route-SortBy="VehicleMakeId" asp-route-OrderBy="@ViewBag.OrderBy">MAKER ID</a></th>
                <th align="center"><a asp-action="Index" asp-route-SortBy="Name" asp-route-OrderBy="@ViewBag.OrderBy">NAME</a></th>
                <th align="center"><a asp-action="Index" asp-route-SortBy="Abrv" asp-route-OrderBy="@ViewBag.OrderBy">ABRV</a></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var mmodel in Model)
            {
                using (Html.BeginForm("Delete", "Model", new { id = mmodel.VehicleModelId}))
                {
            <tr>
                <td align="center">@Html.DisplayFor(modeItem => mmodel.VehicleMakeId)</td>
                <td align="center">@Html.DisplayFor(modeItem => mmodel.Name)</td>
                <td align="center">@Html.DisplayFor(modeItem => mmodel.Abrv)</td>
                <td align="center">
                    <a asp-action="Edit" asp-route-id="@mmodel.VehicleModelId">Edit</a> |
                    <input type="submit" value="Delete" />
                </td>
            </tr>
                }
            }
        </tbody>
    </table>
</div>

<div><a class="nav-link text-dark" asp-area="" asp-controller="Model" asp-action="Create">Create</a></div>
<div>
    @{ if (ViewBag.HasPrevious)
        {
            <a asp-action="Index"
               asp-route-SortBy="@VehicleMVC.Controllers.ModelController.CurrentSort"
               asp-route-OrderBy="@VehicleMVC.Controllers.ModelController.CurrentOrder"
               asp-route-PageNumber="@(VehicleMVC.Controllers.ModelController.CurrentPage - 1)"
               asp-route-Elements="@(VehicleMVC.Controllers.ModelController.ElementsGot - VehicleMVC.Controllers.ModelController.NumberOfElements)"
               class="btn btn-default">
                Previous
            </a>
        }
        if (ViewBag.HasNext)
        {
            <a asp-action="Index"
               asp-route-SortBy="@VehicleMVC.Controllers.ModelController.CurrentSort"
               asp-route-OrderBy="@VehicleMVC.Controllers.ModelController.CurrentOrder"
               asp-route-PageNumber="@(VehicleMVC.Controllers.ModelController.CurrentPage + 1)"
               asp-route-Elements="@(VehicleMVC.Controllers.ModelController.ElementsGot + VehicleMVC.Controllers.ModelController.NumberOfElements)"
               class="btn btn-default">
                Next
            </a>
        }
    }
</div>