VehicleDBProject/VehicleDBWebProject/VehicleMVC/Controllers/MakeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VehicleMVC.Models;
using VehicleService;

namespace VehicleMVC.Controllers
{
    public class MakeController : Controller
    {
        private readonly IVehicleMakeService MakeService;
        private readonly IMapper Mapper;
        public static int NumberOfElements = 3;
        public static int ElementsGot = 0;
        public static int CurrentPage = 1;
        public static string CurrentOrder;
        public static string CurrentSort;


        public MakeController(IVehicleMakeService makeService, IMapper mapper)
        {
            MakeService = makeService;
            Mapper = mapper;
        }

        public IActionResult Index([Bind("SearchName")] Filtering makeFiltering, Sorting sorting, Paging paging)
        {
            if(paging.PageNumber == 1)
            {
                ViewBag.OrderBy = sorting.OrderBy == "DESC" ? "ASC" : "DESC";
                CurrentOrder = sorting.OrderBy;
                CurrentSort = sorting.SortBy;
            }

            if (String.IsNullOrEmpty(sorting.SortBy))
            {
                sorting.SortBy = "Name";
                sorting.OrderBy = "ASC";
            }

            paging.TotalPages = MakeService.CountMakers();
            
            CurrentPage = paging.PageNumber;
            ElementsGot = paging.Elements;
            #region HasNextButton
            if ((ElementsGot + NumberOfElements) < paging.TotalPages)
            {
                ViewBag.HasNext = true;
            }
            else
            {
                ViewBag.HasNext = false;
            }
            #endregion
            #region HasPrevButton
            if (paging.HasPreviousPage)
            {
                ViewBag.HasPrevious = true;
            }
            else
            {
                ViewBag.HasPrevious = false;
            }
            #endregion
            #region Search
            if (!String.IsNullOrEmpty(makeFiltering.SearchName))
            {
                if (!MakeService.HasNameInDatabase(makeFiltering.SearchName))
                {
                    return NotFound(makeFiltering.SearchName + " not Found");
                }
                string countQuery = String.Format("SELECT * FROM dbo.VehicleMakers Where Name = '{0}'", makeFiltering.SearchName);
                paging.TotalPages = MakeService.GetVehicleMakes(countQuery).Count();
                ElementsGot = 0;
                string searchQuery = String.Format("SELECT * FROM dbo.VehicleMakers Where Name = '{0}' ORDER BY {1} {2} OFFSET {3} ROWS FETCH NEXT {4} ROWS ONLY", makeFiltering.SearchName, sorting.SortBy, sorting.OrderBy, ElementsGot, NumberOfElements);
                var searchMake = MakeService.GetVehicleMakes(searchQuery).Select(Mapper.Map<VehicleMakeDTO>);
                #region HasNextButton
                if ((ElementsGot + NumberOfElements) < paging.TotalPages)
                {
                    ViewBag.HasNext = true;
                }
                else
                {
                    ViewBag.HasNext = false;
                }
                #endregion
                #region HasPrevButton
                if (paging.HasPreviousPage)
                {
                    ViewBag.HasPrevious = true;
                }
                else
                {
                    ViewBag.HasPrevious = false;
                }
                #endregion
                return View(searchMake);
            }
            #endregion
            string query = String.Format("SELECT * FROM dbo.VehicleMakers ORDER BY {0} {1} OFFSET {2} ROWS FETCH NEXT {3} ROWS ONLY", sorting.SortBy, sorting.OrderBy, ElementsGot, NumberOfElements);
            var make = MakeService.GetVehicleMakes(query).Select(Mapper.Map<VehicleMake, VehicleMakeDTO>);
            return View(make);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(VehicleMakeDTO makeDTO)
        {
            if (ModelState.IsValid)
            {
                var vehicleMake = Mapper.Map<VehicleMake>(makeDTO);
                await MakeService.AddVehicleMakerAsync(vehicleMake);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (!MakeService.MakeIdExist(id))
            {
                return NotFound();
            }
            VehicleMakeDTO makeDTO = Mapper.Map<VehicleMakeDTO>(await MakeService.GetOneVehicleMakerAsync(id));
            return View(makeDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VehicleMakeDTO vehicleMakeDTO)
        {
            VehicleMake make = Mapper.Map<VehicleMake>(vehicleMakeDTO);
            await MakeService.UpdateAsync(make);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (id.Equals(null))
            {
                return NotFound();
            }

            await MakeService.DeleteVehicleMakerAsync(id);
            
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VehicleDBProject/VehicleDBWebProject/VehicleMVC/Views/Make/Create.cshtml
@model VehicleMakeDTO
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form method="post">
    <div>Name: <input asp-for="Name" /></div>
    <div>Abrv: <input asp-for="Abrv" /></div>
    <input type="submit" />
</form>

VehicleDBProject/VehicleDBWebProject/VehicleMVC/Views/Make/Edit.cshtml
@model VehicleMakeDTO
@{
    ViewData["Title"] = "Edit";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>@Model.Name</legend>

        @Html.HiddenFor(model => model.VehicleMakeId)

        <div>@Html.LabelFor(model => model.Name)</div>
        <div>@Html.EditorFor(model => model.Name)</div>

        <div>@Html.LabelFor(model => model.Abrv)</div>
        <div>@Html.EditorFor(model => model.Abrv)</div>

        <p><input type="submit" value="Save"/></p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VehicleDBProject/VehicleDBWebProject/VehicleMVC/Views/Make/Index.cshtml
@model IEnumerable<VehicleMakeDTO>
@{
    ViewData["Title"] = "Vehicle Makers";
}

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by Name: <input type="text" name="SearchName"/>
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<div>
    <table border="1">
        <thead>
            <tr>
                <th align="center"><a asp-action="Index" asp-route-SortBy="Name" asp-route-OrderBy="@ViewBag.OrderBy">NAME</a></th>
                <th align="center"><a asp-action="Index" asp-route-SortBy="Abrv" asp-route-OrderBy="@ViewBag.OrderBy">ABRV</a></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var make in Model)
            {
                using (Html.BeginForm("Delete", "Make", new { id = make.VehicleMakeId }))
                {
                    <tr>
                        <td align="center">@Html.DisplayFor(modeItem => make.Name)</td>
                        <td align="center">@Html.DisplayFor(modeItem => make.Abrv)</td>
                        <td align="center">
                            <a asp-action="Edit" asp-route-id="@make.VehicleMakeId">Edit</a> |
                            <input type="submit" value="Delete" />
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<div><a class="nav-link text-dark" asp-area="" asp-controller="Make" asp-action="Create">Create</a></div>

<div>
    @{ if (ViewBag.HasPrevious)
        {
            <a asp-action="Index"
               asp-route-SortBy="@VehicleMVC.Controllers.MakeController.CurrentSort"
               asp-route-OrderBy="@VehicleMVC.Controllers.MakeController.CurrentOrder"
               asp-route-PageNumber="@(VehicleMVC.Controllers.MakeController.CurrentPage - 1)"
               asp-route-Elements="@(VehicleMVC.Controllers.MakeController.ElementsGot - VehicleMVC.Controllers.MakeController.NumberOfElements)"
               class="btn btn-default">
                Previous
            </a>
        }
        if (ViewBag.HasNext)
        {
            <a asp-action="Index"
               asp-route-SortBy="@VehicleMVC.Controllers.MakeController.CurrentSort"
               asp-route-OrderBy="@VehicleMVC.Controllers.MakeController.CurrentOrder"
               asp-route-PageNumber="@(VehicleMVC.Controllers.MakeController.CurrentPage + 1)"
               asp-route-Elements="@(VehicleMVC.Controllers.MakeController.ElementsGot + VehicleMVC.Controllers.MakeController.NumberOfElements)"
               class="btn btn-default">
                Next
            </a>
        }
    }
</div>